### ISSUE TITLE
mailslurp-swagger-sdk-ts dependency: replace git by regular npm version

### ISSUE THREAD

**Issue by jpnovaissn** [mailslurp/mailslurp-client#10] opened 2019-07-26 13:00 UTC
This package cannot be installed in Nodejs docker images that don't git available.

It would be good to publish [mailslurp-swagger-sdk-ts](https://github.com/mailslurp/swagger-sdk-typescript-fetch) to npm and update [package.json](https://github.com/mailslurp/mailslurp-client-ts-js/blob/master/package.json#L15) to rely on npm instead of git.

**Comment by jinjor** [comment] 2019-07-31 11:38
+1 to this.

Our CI build suddenly started to fail because of the git dependency.

We got this error on executing `npm install`.

```
#!/bin/bash -eo pipefail
cd webui && npm install
Unhandled rejection Error: Command failed: /usr/bin/git checkout 2a57fd0e84e74f8a3933c092f10bdf0d5d940923
fatal: reference is not a tree: 2a57fd0e84e74f8a3933c092f10bdf0d5d940923

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-31T10_47_47_290Z-debug.log
Exited with code 1
```

package-lock.json has this dependency.

```
    "mailslurp-swagger-sdk-ts": {
      "version": "git+https://github.com/mailslurp/swagger-sdk-typescript-fetch.git#2a57fd0e84e74f8a3933c092f10bdf0d5d940923",
      "from": "git+https://github.com/mailslurp/swagger-sdk-typescript-fetch.git#2a57fd0e84e74f8a3933c092f10bdf0d5d940923",
      "dev": true,
      "requires": {
        "portable-fetch": "^3.0.0"
      }
    },
```

I fix it by running `npm install -D mailslurp-client` (which updates package-lock.json too).

**Comment by drptbl** [comment] 2019-08-04 11:33
+1.. this shouldn't ever happen.

**Comment by traverse** [comment] 2019-08-05 09:03
Can this get some priority maybe? Third time in like 2 weeks CI builds start failing randomly because of this. 😞

**Comment by jackmahoney** [comment] 2019-08-09 14:50
Hi everyone. Sorry for the delay.

I am really sorry for this issue. It is now fixed. The subpackage has been published to NPM and the github dependency completely removed.

Please [see the explanation here](https://github.com/mailslurp/mailslurp-client-ts-js/issues/11).

cc
@traverse 
@drptbl 
@jinjor 
@jpnovaissn

**Comment by jinjor** [comment] 2019-08-09 15:44
I confirmed this problem has been fixed. Thank you!

**Closed as completed** 2019-08-10 08:42 UTC
